# create service directories
- name: create service directories
  file:
    path: "{{ root_path }}/{{ item.name }}"
    state: directory
  loop: "{{ enabled_services }}"

# copy docker-compose
- name: copy docker-compose files
  copy:
    src: "{{ services_path }}/{{ item.name }}/docker-compose.yaml"
    dest: "{{ root_path }}/{{ item.name }}/docker-compose.yaml"
  loop: "{{ enabled_services }}"

# env files
- name: generate env files if template exists
  template:
    src: "{{ services_path }}/{{ item.name }}/.env.j2"
    dest: "{{ root_path }}/{{ item.name }}/.env"
  loop: "{{ enabled_services }}"
  ignore_errors: true

# start services
- name: start docker services
  community.docker.docker_compose_v2:
    project_src: "{{ root_path }}/{{ item.name }}"
    state: present
  loop: "{{ enabled_services }}"
