- name: Ensure external Docker networks exist
  community.docker.docker_network:
    name: "{{ item }}"
    state: present
  loop: "{{ docker_networks }}"

- name: create service directories
  file:
    path: "{{ root_path }}/{{ item.name }}"
    state: directory
  loop: "{{ enabled_services }}"

- name: create data directories
  file:
    path: "{{ data_path }}/{{ item.name }}"
    state: directory
  loop: "{{ services }}"

- name: copy docker-compose files
  copy:
    src: "{{ services_path }}/{{ item.name }}/docker-compose.yaml"
    dest: "{{ root_path }}/{{ item.name }}/docker-compose.yaml"
  loop: "{{ enabled_services }}"

- name: generate env file per service
  template:
    src: "{{ services_path }}/service.env.j2"
    dest: "{{ root_path }}/{{ item.name }}/.env"
  loop: "{{ enabled_services }}"

- name: start docker services
  community.docker.docker_compose_v2:
    project_src: "{{ root_path }}/{{ item.name }}"
    state: present
  loop: "{{ enabled_services }}"

- name: stop disabled services
  community.docker.docker_compose_v2:
    project_src: "{{ root_path }}/{{ item.name }}"
    state: absent
  loop: "{{ services | selectattr('enabled', 'equalto', false) | list }}"
