all:
  hosts:
    contabo:
      ansible_host: omrin # resolves via ~/.ssh/config
      ansible_user: aditya
      ansible_python_interpreter: /usr/bin/python3
      ansible_ssh_common_args: >-
        -o StrictHostKeyChecking=no
        -o UserKnownHostsFile=/dev/null
