new_user: aditya
ssh_port: 22 # change later
domain: "omrin.in"
server_hostname: omrin

root_path: "/home/{{ new_user }}/Omrin"
services_path: "{{ playbook_dir }}/../services"
data_path: "/data/omrin"

ssh_public_key_path: "~/.ssh/personal.pub"

onedrive_backup_path: "Omrin-Backups" # folder name created in OneDrive root
backup_schedule: "00:30" # systemd OnCalendar time, server-local time CEST

backup_exclude_paths:
  - "arr-stack/downloads/**" # transient torrent staging, not worth backing up

arr_stack_enabled: false

services:
  - name: traefik
    enabled: true
  - name: syncbrowser
    enabled: true
  - name: linkding
    enabled: true
  - name: radicale
    enabled: true
  - name: uptime-kuma
    enabled: true
  - name: ntfy
    enabled: true
  - name: vaultwarden
    enabled: true
  - name: kavita
    enabled: true
  - name: beszel
    enabled: true
  - name: omni-tools
    enabled: true
  - name: wallabag
    enabled: true
  - name: excalidash
    enabled: true

enabled_services: "{{ services | rejectattr('enabled', 'equalto', false) | list }}"

apt_tools:
  - fish
  - btop
  - htop
  - tmux
  - git
  - curl
  - wget
  - unzip
  - ncdu
  - tree
  - jq
  - mosh
