- hosts: all
  become: true

  vars_files:
    - ../group_vars/all.yaml
    - ../group_vars/secrets.yaml

  roles:
    - role: docker
      tags: docker
    - role: firewall
      tags: firewall
    - role: ssh
      tags: ssh
    - role: services
      tags: services
