services:
  wallabag:
    image: wallabag/wallabag
    container_name: wallabag
    restart: unless-stopped
    environment:
      SYMFONY__ENV__DATABASE_DRIVER: pdo_sqlite
      SYMFONY__ENV__DOMAIN_NAME: https://articles.${DOMAIN:?}
      SYMFONY__ENV__SERVER_NAME: "Omrin Wallabag"
      SYMFONY__ENV__FROM_EMAIL: wallabag@${DOMAIN:?}
      SYMFONY__ENV__FOSUSER_REGISTRATION: "false"
    volumes:
      - ${DATA_PATH:?}/wallabag/data:/var/www/wallabag/data
      - ${DATA_PATH:?}/wallabag/images:/var/www/wallabag/web/assets/images
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.wallabag.rule=Host(`articles.${DOMAIN:?}`)
      - traefik.http.services.wallabag.loadbalancer.server.port=80

networks:
  proxy:
    external: true